### ISSUE TITLE
Poprawienie ucinania tekstu podpowiedzi wyszukiwania

### ISSUE THREAD

**Issue by Grzybojad** [SilverNETGroupSGGW/kampus_sggw#53]
Jeżeli tekst wyszukiwania zostanie ucięty na długim słowie, to tekst może wyglądać na dziwnie wcześnie ucięty.

Może da się zmienić, żeby ... mogło ucinać tekst w pół słowa, nie tylko na spacji.

![obraz](https://user-images.githubusercontent.com/18161644/119859203-769ab180-bf15-11eb-9e21-b21d6237a443.png)

**Comment by martamazurkiewicz** [comment]
Tekst jest ucinany też w FilterButton (po wyszukaniu, albo przefiltrowaniu obiektów mapy) i w HistoryTile
